<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de usuarios</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>user/grabaruser"
									method='post'>
									<div class="form-group">
										<label>idUser</label> <input type='text'
											name=idUser
											value="<?php echo $this->user->idUser ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>firstName</label> <input type='text'
											name='firstName' class="form-control"
											value="<?php echo $this->user->firstName ?>">
									</div>

									<div class="form-group">
										<label>lastName</label> <input type='text'
											name='lastName' class="form-control"
											value="<?php echo $this->user->lastName ?>">
									</div>
									<div class="form-group">
										<label>email</label> <input type='text'
											name='email' class="form-control"
											value="<?php echo $this->user->email ?>">
									</div>
									<div class="form-group">
										<label>dateReg</label> <input type='text'
											name='dateReg' class="form-control"
											value="<?php echo $this->user->dateReg ?>">
									</div>					
									<div class="form-group">
										<label>dateMod</label> <input type='text'
											name='dateMod' class="form-control"
											value="<?php echo $this->user->dateMod ?>">
									</div>
									
									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
