
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-16">


				<h2>Tabla usuarios</h2>



			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-16">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="example">
								<thead>
									<tr>
										<th>idUser</th>
										<th>firstName</th>
										<th>lastName</th>
										<th>email</th>
										<th>dateReg</th>
										<th>dateMod</th>
										<th>Opciones</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
                                    <?php while($reg = $this->users->fetch_object()):?>
                                        <tr class="odd gradeX">
										<td><?php echo $reg->idUser ?></td>
										<td><?php echo $reg->firstName ?></td>
										<td><?php echo $reg->lastName ?></td>
										<td><?php echo $reg->email ?></td>
										<td><?php echo $reg->dateReg ?></td>
										<td class="center"><?php echo $reg->dateMod?></td>
										<td><a href="<?php echo BASE_URL?>user/editar/<?php echo $reg->idUser?>">Editar</a> </td>
										<td><a href="<?php echo BASE_URL?>user/borrar/<?php echo $reg->idUser?>">Borrar</a></td>
									</tr>
                                    <?php endwhile;?>    
                                   
                                   </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>
















