<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de detalle de órdenes</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>orderdetail/grabarorderdetail"
									method='post'>
									<div class="form-group">
										<label>orderNumber</label> <input type='text'
											name='orderNumber'
											value="<?php echo $this->orderdetail->orderNumber ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>productCode</label> <input type='text'
											name='productCode' class="form-control"
											value="<?php echo $this->orderdetail->productCode ?>">
									</div>

									<div class="form-group">
										<label>quantityOrdered</label> <input type='text'
											name='quantityOrdered' class="form-control"
											value="<?php echo $this->orderdetail->quantityOrdered ?>">
									</div>
									<div class="form-group">
										<label>priceEach</label> <input type='text'
											name='priceEach' class="form-control"
											value="<?php echo $this->orderdetail->priceEach ?>">
									</div>
									<div class="form-group">
										<label>orderLineNumber</label> <input type='text'
											name='orderLineNumber' class="form-control"
											value="<?php echo $this->orderdetail->orderLineNumber ?>">
									</div>
									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
