
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-16">


				<h2>Tabla detalle de las órdenes</h2>



			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-16">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="example">
								<thead>
									<tr>
										<th>orderNumber</th>
										<th>productCode</th>
										<th>quantityOrdered</th>
										<th>priceEach</th>
										<th>orderLineNumber</th>
										<th>Opciones</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
                                    <?php while($reg = $this->orderdetails->fetch_object()):?>
                                        <tr class="odd gradeX">
										<td><?php echo $reg->orderNumber ?></td>
										<td><?php echo $reg->productCode ?></td>
										<td><?php echo $reg->quantityOrdered ?></td>
										<td><?php echo $reg->priceEach ?></td>
										<td class="center"><?php echo $reg->orderLineNumber ?></td>
										<td><a href="<?php echo BASE_URL?>orderdetail/editar/<?php echo $reg->orderNumber?>">Editar</a> </td>
										<td><a href="<?php echo BASE_URL?>orderdetail/borrar/<?php echo $reg->orderNumber?>">Borrar</a></td>
									</tr>
                                    <?php endwhile;?>    
                                   
                                   </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>
















