<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de oficinas</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>office/grabaroffice"
									method='post'>
									<div class="form-group">
										<label>officeCode</label> <input type='text'
											name='officeCode'
											value="<?php echo $this->office->officeCode ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>city</label> <input type='text'
											name='city' class="form-control"
											value="<?php echo $this->office->city ?>">
									</div>

									<div class="form-group">
										<label>phone</label> <input type='text'
											name='phone' class="form-control"
											value="<?php echo $this->office->phone ?>">
									</div>
									<div class="form-group">
										<label>addressLine1</label> <input type='text'
											name='addressLine1' class="form-control"
											value="<?php echo $this->office->addressLine1 ?>">
									</div>
									<div class="form-group">
										<label>addressLine2</label> <input type='text'
											name='addressLine2' class="form-control"
											value="<?php echo $this->office->addressLine2 ?>">
									</div>
									<div class="form-group">
										<label>state</label>
										<textarea class="form-control" name='state' rows="3"><?php echo $this->office->state ?></textarea>
									</div>
									<div class="form-group">
										<label>country</label> <input type='text'
											name='country' class="form-control"
											value="<?php echo $this->office->country ?>">
									</div>
									<div class="form-group">
										<label>postalCode</label> <input type='text' name='postalCode'
											class="form-control"
											value="<?php echo $this->office->postalCode ?>">
									</div>
									<div class="form-group">
										<label>territory</label> <input type='text' name='territory'
											class="form-control"
											value="<?php echo $this->office->territory ?>">
									</div>
									
									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
