<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de órdenes</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>order/grabarorder"
									method='post'>
									<div class="form-group">
										<label>orderNumber</label> <input type='text'
											name=orderNumber
											value="<?php echo $this->order->orderNumber ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>orderDate</label> <input type='text'
											name='orderDate' class="form-control"
											value="<?php echo $this->order->orderDate ?>">
									</div>

									<div class="form-group">
										<label>requiredDate</label> <input type='text'
											name='requiredDate' class="form-control"
											value="<?php echo $this->order->requiredDate ?>">
									</div>
									<div class="form-group">
										<label>shippedDate</label> <input type='text'
											name='shippedDate' class="form-control"
											value="<?php echo $this->order->shippedDate ?>">
									</div>
									<div class="form-group">
										<label>status</label> <input type='text'
											name='status' class="form-control"
											value="<?php echo $this->order->status ?>">
									</div>
									<div class="form-group">
										<label>comments</label> <input type='text'
											name='comments' class="form-control"
											value="<?php echo $this->order->comments ?>">
									</div>
									<div class="form-group">
										<label>customerNumber</label> <input type='text' name='customerNumber'
											class="form-control"
											value="<?php echo $this->order->customerNumber ?>">
									</div>
									
									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
