
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-16">


				<h2>Tabla clientes</h2>



			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-16">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="example">
								<thead>
									<tr>
										<th>customerNumber</th>
										<th>customerName</th>
										<th>contactLastName</th>
										<th>contactFirstName</th>
										<th>phone</th>
										<th>addressLine1</th>
										<th>addressLine2</th>
										<th>city</th>
										<th>state</th>
										<th>postalCode</th>
										<th>country</th>
										<th>salesRepEmployeeNumber</th>
										<th>creditLimit</th>
										<th>Opciones</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
                                    <?php while($reg = $this->customers->fetch_object()):?>
                                        <tr class="odd gradeX">
										<td><?php echo $reg->customerNumber ?></td>
										<td><?php echo $reg->customerName ?></td>
										<td><?php echo $reg->contactLastName ?></td>
										<td><?php echo $reg->contactFirstName ?></td>
										<td><?php echo $reg->phone ?></td>
										<td><?php echo $reg->addressLine1 ?></td>
										<td><?php echo $reg->addressLine2 ?></td>
										<td><?php echo $reg->city ?></td>
										<td><?php echo $reg->state ?></td>
										<td class="center"><?php echo $reg->postalCode ?></td>
										<td><?php echo $reg->country ?></td>
										<td class="center"><?php echo $reg->salesRepEmployeeNumber?></td>
										<td><?php echo $reg->creditLimit ?></td>
										<td><a href="<?php echo BASE_URL?>customer/editar/<?php echo $reg->customerNumber?>">Editar</a> </td>
										<td><a href="<?php echo BASE_URL?>customer/borrar/<?php echo $reg->customerNumber?>">Borrar</a></td>
									</tr>
                                    <?php endwhile;?>    
                                   
                                   </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>
















