<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de productos</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>product/grabarproducto"
									method='post'>
									<div class="form-group">
										<label>ProductCode</label> <input type='text'
											name='productCode'
											value="<?php echo $this->producto->productCode ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>ProductName</label> <input type='text'
											name='productName' class="form-control"
											value="<?php echo $this->producto->productName?>">
									</div>

									<div class="form-group">
										<label>ProductLine</label> <input type='text'
											name='productLine' class="form-control"
											value="<?php echo $this->producto->productLine?>">
									</div>
									<div class="form-group">
										<label>ProductScale</label> <input type='text'
											name='productScale' class="form-control"
											value="<?php echo $this->producto->productScale?>">
									</div>
									<div class="form-group">
										<label>ProductVendor</label> <input type='text'
											name='productVendor' class="form-control"
											value="<?php echo $this->producto->productVendor?>">
									</div>
									<div class="form-group">
										<label>ProductDescription</label>
										<textarea class="form-control" name='productDescription' rows="3"><?php echo $this->producto->productDescription?></textarea>
									</div>
									<div class="form-group">
										<label>quantityStock</label> <input type='text'
											name='quantityInStock' class="form-control"
											value="<?php echo $this->producto->quantityInStock?>">
									</div>
									<div class="form-group">
										<label>buyPrice</label> <input type='text' name='buyPrice'
											class="form-control"
											value="<?php echo $this->producto->buyPrice ?>">
									</div>
									<div class="form-group">
										<label>MSRP</label> <input type='text' name='MSRP'
											class="form-control"
											value="<?php echo $this->producto->MSRP?>">
									</div>

									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
