
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-16">


				<h2>Tabla productos</h2>



			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-16">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="example">
								<thead>
									<tr>
										<th>Codigo</th>
										<th>Descripcion</th>
										<th>Linea</th>
										<th>Precio</th>
										<th>Stock</th>
										<th>Opciones</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
                                    <?php while($reg = $this->productos->fetch_object()):?>
                                        <tr class="odd gradeX">
										<td><?php echo $reg->productCode ?></td>
										<td><?php echo $reg->productName ?></td>
										<td><?php echo $reg->productLine ?></td>
										<td class="center"><?php echo $reg->buyPrice ?></td>
										<td class="center"><?php echo $reg->quantityInStock?></td>
										<td><a href="<?php echo BASE_URL?>product/editar/<?php echo $reg->productCode?>">Editar</a> |</td>
										<td><a href="<?php echo BASE_URL?>product/borrar/<?php echo $reg->productCode?>">Borrar</a></td>
									</tr>
                                    <?php endwhile;?>    
                                   
                                   </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>
















