<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Edicion de pagos</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<form role="form"
									action="<?php echo BASE_URL ?>payment/grabarpayment"
									method='post'>
									<div class="form-group">
										<label>customerNumber</label> <input type='text'
											name=customerNumber
											value="<?php echo $this->payment->customerNumber ?>"
											class="form-control" readonly>

									</div>
									<div class="form-group">
										<label>checkNumber</label> <input type='text'
											name='checkNumber' class="form-control"
											value="<?php echo $this->payment->checkNumber ?>">
									</div>

									<div class="form-group">
										<label>paymentDate</label> <input type='text'
											name='paymentDate' class="form-control"
											value="<?php echo $this->payment->paymentDate ?>">
									</div>
									<div class="form-group">
										<label>amount</label> <input type='text'
											name='amount' class="form-control"
											value="<?php echo $this->payment->amount ?>">
									</div>
									
									<br>
									<button type="submit" class="btn btn-default">Submit Button</button>
									<button type="reset" class="btn btn-default">Reset Button</button>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
