
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-16">


				<h2>Tabla de pagos</h2>



			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-16">
				<div class="panel panel-default">
					<div class="panel-heading"></div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="example">
								<thead>
									<tr>
										<th>customerNumber</th>
										<th>checkNumber</th>
										<th>paymentDate</th>
										<th>amount</th>
										<th>Opciones</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
                                    <?php while($reg = $this->payments->fetch_object()):?>
                                        <tr class="odd gradeX">
										<td><?php echo $reg->customerNumber ?></td>
										<td><?php echo $reg->checkNumber ?></td>
										<td><?php echo $reg->paymentDate ?></td>
										<td><?php echo $reg->amount ?></td>
										<td><a href="<?php echo BASE_URL?>payment/editar/<?php echo $reg->customerNumber?>">Editar</a> </td>
										<td><a href="<?php echo BASE_URL?>payment/borrar/<?php echo $reg->customerNumber?>">Borrar</a></td>
									</tr>
                                    <?php endwhile;?>    
                                   
                                   </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>
















